services:
  db:
    image: postgres:15-alpine
    container_name: recruitment_db_dev
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-recruitment_platform}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - recruitment_network_dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: recruitment_pgadmin_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - recruitment_network_dev

  redis:
    image: redis:alpine
    container_name: recruitment_redis_dev
    networks:
      - recruitment_network_dev

  backend:
    build:
      context: ./recruitment-be
      dockerfile: Dockerfile
    container_name: recruitment_backend_dev
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-recruitment_platform}?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_FROM=${MAIL_FROM}
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - recruitment_network_dev

  frontend:
    build:
      context: ./recruitment-fe
      dockerfile: Dockerfile
    container_name: recruitment_frontend_dev
    restart: always
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - recruitment_network_dev

networks:
  recruitment_network_dev:
    driver: bridge

volumes:
  postgres_data_dev:
